---
- name: Deploy cluster
  hosts: localhost
  connection: local

  tasks:
  - name: Basic deploy of a service
    community.general.terraform:
      project_path: '{{ project_dir }}'
      state: present
